image: ubuntu:15.10
variables:
  CXX: gcc-5
  CC: gcc-5
stages:
  - build
  - cleanup

toxvpn:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq git libcap-dev libnl-route-3-dev libnl-3-dev libjansson-dev libsodium-dev gcc-5 g++-5
    - git clone git://github.com/irungentoo/toxcore.git > /dev/null
    - pushd toxcore
    - autoreconf -i
    - ./configure
    - make -j3
    - make check
    - make install
    - popd
    - make all

  artifacts:
    name: toxvpn
    untracked: true
  only:
    - master

toxvpn-clean:
  stage: cleanup
  script:
    - make clean
  only:
    - master
