language: c
sudo: true
dist: trusty
compiler:
- gcc
os:
- linux
addons:
  apt:
    packages:
    - libcap-dev
    - libnl-route-3-dev
    - libnl-3-dev
    - libjansson-dev

before_install:
  - echo $LANG
  - echo $LC_ALL

before_script:
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - ./autogen.sh
  - ./configure
  - make check -j3
  - sudo make install
  - popd
  - git clone git://github.com/irungentoo/toxcore.git > /dev/null
  - pushd toxcore
  - autoreconf -i
  - ./configure
  - make -j3
  - make check
  - sudo make install
  - popd

script:
  - make all

branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email: false
