language: ะก
sudo: true
dist: trusty
compiler:
- gcc-5
os:
- linux
env: CC=gcc-5 CXX=g++-5
addons:
  apt:
    packages:
      - g++-5
      - libcap-dev
      - libnl-route-3-dev
      - libnl-3-dev
      - libjansson-dev
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - echo $LANG
  - echo $LC_ALL

before_script:
  - git clone git://github.com/jedisct1/libsodium.git > /dev/null
  - pushd libsodium
  - ./autogen.sh
  - ./configure
  - make check -j3
  - sudo make install
  - popd
  - git clone git://github.com/irungentoo/toxcore.git > /dev/null
  - pushd toxcore
  - autoreconf -i
  - ./configure
  - make -j3
  - make check
  - sudo make install
  - popd

script:
  - make all

branches:
  only:
  - master
  - "/^v\\d+\\./"

notifications:
  email: false
